# Generated by Django 2.2.7 on 2019-11-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordonnee',
            old_name='posotion',
            new_name='position',
        ),
    ]
