# Generated by Django 2.2.7 on 2019-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0004_auto_20191117_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='distance',
            field=models.FloatField(verbose_name='Distance :'),
        ),
    ]
