# Generated by Django 2.2.7 on 2019-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0005_auto_20191118_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='distance',
            field=models.FloatField(default=0, verbose_name='Distance :'),
        ),
    ]
