# Generated by Django 2.2.7 on 2019-11-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0006_auto_20191118_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-create_date',)},
        ),
    ]
