# Generated by Django 2.2.7 on 2019-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0008_auto_20191118_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordonnee',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='coordonnees',
            field=models.ManyToManyField(to='geoLocApp.Coordonnee'),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance :'),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
