# Generated by Django 2.2.7 on 2019-11-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocApp', '0009_auto_20191122_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='coordonnees',
        ),
    ]
