# Generated by Django 2.2.7 on 2019-11-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitute :')),
                ('latitude', models.FloatField(verbose_name='Latitude :')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la requete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordonnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitute :')),
                ('latitude', models.FloatField(verbose_name='Latitude :')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la requete')),
                ('distance', models.FloatField(default=0, verbose_name='Distance :')),
                ('posotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoLocApp.Position')),
            ],
            options={
                'ordering': ('-distance',),
            },
        ),
    ]
